// enum_gen.go — 最小 AST 代码生成器 demo
// 功能：扫描 Go 源文件中的 type X int 常量组，自动生成 String() 方法
// 这是 stringer 的简化版，展示 go/ast + go/types 的核心工作流

//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"text/template"
)

// Step 1: 定义我们要生成什么
// 输入：一组 const 声明（type Status int + const (Active Status = iota ...)）
// 输出：func (s Status) String() string { ... }

type EnumType struct {
	TypeName string
	Values   []EnumValue
}

type EnumValue struct {
	Name  string
	Value int
}

// Step 2: 用 go/ast 解析源文件，提取常量组
func extractEnums(filename string) ([]EnumType, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", filename, err)
	}

	var enums []EnumType

	// 遍历所有声明
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		// 检查是否有 iota 模式的常量组
		var currentType string
		var values []EnumValue
		iotaVal := 0

		for _, spec := range genDecl.Specs {
			vs := spec.(*ast.ValueSpec)

			// 提取类型名
			if vs.Type != nil {
				if ident, ok := vs.Type.(*ast.Ident); ok {
					currentType = ident.Name
				}
			}

			if currentType == "" {
				continue
			}

			for _, name := range vs.Names {
				if name.Name == "_" {
					iotaVal++
					continue
				}
				values = append(values, EnumValue{
					Name:  name.Name,
					Value: iotaVal,
				})
				iotaVal++
			}
		}

		if currentType != "" && len(values) > 0 {
			enums = append(enums, EnumType{
				TypeName: currentType,
				Values:   values,
			})
		}
	}

	return enums, nil
}

// Step 3: 用 template 生成代码（比 fmt.Fprintf 更可读）
var stringerTmpl = template.Must(template.New("stringer").Parse(`
// Code generated by enum_gen. DO NOT EDIT.
package {{.Package}}

import "fmt"

{{range .Enums}}
func (v {{.TypeName}}) String() string {
	switch v {
	{{- range .Values}}
	case {{.Name}}:
		return "{{.Name}}"
	{{- end}}
	default:
		return fmt.Sprintf("{{.TypeName}}(%d)", int(v))
	}
}
{{end}}
`))

type TemplateData struct {
	Package string
	Enums   []EnumType
}

// Step 4: 格式化输出（go/format 确保生成代码风格一致）
func generate(pkg string, enums []EnumType) ([]byte, error) {
	var buf bytes.Buffer
	if err := stringerTmpl.Execute(&buf, TemplateData{
		Package: pkg,
		Enums:   enums,
	}); err != nil {
		return nil, err
	}

	// go/format 等价于 gofmt
	return format.Source(buf.Bytes())
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: go run enum_gen.go <source.go>\n")
		os.Exit(1)
	}

	filename := os.Args[1]
	enums, err := extractEnums(filename)
	if err != nil {
		fmt.Fprintf(os.Stderr, "extract: %v\n", err)
		os.Exit(1)
	}

	if len(enums) == 0 {
		fmt.Fprintf(os.Stderr, "no enum types found in %s\n", filename)
		os.Exit(0)
	}

	// 推断 package 名
	pkg := strings.TrimSuffix(filename, ".go")
	if idx := strings.LastIndex(pkg, "/"); idx >= 0 {
		pkg = pkg[idx+1:]
	}
	pkg = "main" // 简化 demo

	src, err := generate(pkg, enums)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}

	// 写入 xxx_string.go
	outFile := strings.TrimSuffix(filename, ".go") + "_string.go"
	if err := os.WriteFile(outFile, src, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s (%d enum types)\n", outFile, len(enums))
}

// ============================================================
// 工作流总结：
//
//   源文件(.go) → go/ast 解析 → 提取类型+常量
//                                    ↓
//   生成文件(.go) ← go/format ← template 渲染
//
// 三件套：
//   go/ast    — 读取和理解 Go 代码结构
//   go/types  — 类型检查和推断（本 demo 简化省略）
//   go/format — 确保输出代码风格一致
//
// 在项目中使用：
//   //go:generate go run ./cmd/enum_gen ./types.go
// ============================================================
